name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name ECS_PDF_Highlighter ecs_pdf_highlighter.py
          echo "Built EXE:"
          dir dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ECS_PDF_Highlighter
          path: dist/ECS_PDF_Highlighter.exe
