name: Build ECS PDF Highlighter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ecs_pdf_highlighter.py"
      - "ecs_pdf_highlighter.spec"
      - "requirements.txt"
      - ".github/workflows/build.yml"

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force .\build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force .\dist -ErrorAction SilentlyContinue

      - name: Build with spec
        run: pyinstaller --noconfirm ecs_pdf_highlighter.spec

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecs_pdf_highlighter_exe
          path: dist/ecs_pdf_highlighter.exe
